[master]
  master01 ansible_host=<master01_ip> ansible_user=<user>
  
  [workers]
  node01 ansible_host=<node01_ip> ansible_user=<user>
  node02 ansible_host=<node02_ip> ansible_user=<user>
  node03 ansible_host=<node03_ip> ansible_user=<user>
  node04 ansible_host=<node04_ip> ansible_user=<user>
  node05 ansible_host=<node05_ip> ansible_user=<user>
  node06 ansible_host=<node06_ip> ansible_user=<user>
  node07 ansible_host=<node07_ip> ansible_user=<user>
  node08 ansible_host=<node08_ip> ansible_user=<user>
  node09 ansible_host=<node09_ip> ansible_user=<user>