# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app: httpd-opensearch
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: httpd-opensearch
  ports:
  - port: 443
    name: https
  - port: 9200
    name: open
